name: parkinson_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - numpy=1.26.2
  - pandas=2.1.4
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - biopython=1.83
  - openpyxl=3.1.2
  - pip
  - pip:
    - pip
    - statsmodels==0.14.1
    - lifelines==0.28.0
    - scikit-posthocs==0.8.1
    - scikit-learn==1.3.2
    - xgboost==2.0.3
    - umap-learn==0.5.5
    - joblib==1.3.2
    - requests==2.26.0
